#!/usr/bin/env bash
# Script that configure HAproxy on your lb-01 server.

apt-get update
apt-get install -y haproxy
cp /etc/haproxy/haproxy.cfg /etc/haproxy/haproxy.cfg.default
echo "
listen 42876-lb-01
	bind *:80
	mode http
	balance roundrobin
	option httpclose
	option forwardfor
	server 42876-web-01 35.172.165.29 check
	server 42876-web-02 100.25.146.82 check
" >> /etc/haproxy/haproxy.cfg
service haproxy restart
